<?= $this->extend('layouts/admin') ?>
<?= $this->section('contenido') ?>
<section class="page-heading"><div><a class="back-link" href="<?= base_url('admin/usuarios') ?>">← Volver a usuarios</a><h1><?= esc($titulo) ?></h1><p class="muted">Configura la identidad, rol y estado de la cuenta.</p></div></section>
<?php $errors = session('errors') ?? []; ?><?php if (session()->has('error')): ?><div class="alert error"><?= esc(session('error')) ?></div><?php endif ?><?php if ($errors !== []): ?><div class="alert error"><strong>Revisa la información:</strong><ul><?php foreach ($errors as $error): ?><li><?= esc($error) ?></li><?php endforeach ?></ul></div><?php endif ?>
<form class="panel event-form" action="<?= esc($accion) ?>" method="post"><?= csrf_field() ?><div class="form-section"><div class="form-section-title"><h2>Datos del usuario</h2><p>El rol determina las funciones disponibles dentro del sistema.</p></div><div class="form-grid">
<label class="field"><span>Nombres *</span><input type="text" name="nombres" maxlength="100" required value="<?= esc(old('nombres', $usuarioEditado['nombres'] ?? '')) ?>"></label>
<label class="field"><span>Apellidos *</span><input type="text" name="apellidos" maxlength="100" required value="<?= esc(old('apellidos', $usuarioEditado['apellidos'] ?? '')) ?>"></label>
<label class="field"><span>Correo electrónico *</span><input type="email" name="email" maxlength="190" required value="<?= esc(old('email', $usuarioEditado['email'] ?? '')) ?>"></label>
<label class="field"><span>Teléfono</span><input type="text" name="telefono" maxlength="25" value="<?= esc(old('telefono', $usuarioEditado['telefono'] ?? '')) ?>"></label>
<label class="field"><span>Rol *</span><select name="rol_id" required><option value="">Selecciona un rol</option><?php foreach ($roles as $rol): ?><?php $selected = (string) old('rol_id', $usuarioEditado['rol_id'] ?? ''); ?><option value="<?= esc((string) $rol['id']) ?>" <?= $selected === (string) $rol['id'] ? 'selected' : '' ?>><?= esc($rol['nombre']) ?></option><?php endforeach ?></select></label>
<label class="field"><span>Estado *</span><select name="estado" required><?php $estado = old('estado', $usuarioEditado['estado'] ?? 'activo'); ?><?php foreach (['activo' => 'Activo', 'inactivo' => 'Inactivo', 'bloqueado' => 'Bloqueado'] as $value => $label): ?><option value="<?= $value ?>" <?= $estado === $value ? 'selected' : '' ?>><?= $label ?></option><?php endforeach ?></select></label>
<?php if ($usuarioEditado === null): ?><label class="field"><span>Contraseña *</span><input type="password" name="password" minlength="10" maxlength="255" required autocomplete="new-password"></label><label class="field"><span>Confirmar contraseña *</span><input type="password" name="password_confirm" minlength="10" maxlength="255" required autocomplete="new-password"></label><p class="password-help full">Mínimo 10 caracteres, con mayúscula, minúscula, número y símbolo.</p><?php endif ?>
</div></div><footer class="form-actions"><a class="secondary-button" href="<?= base_url('admin/usuarios') ?>">Cancelar</a><button class="primary-button borderless" type="submit">Guardar usuario</button></footer></form>
<?= $this->endSection() ?>
